In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
dependent=dataset[['classification_yes']]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [11]:
param_grid={
    'criterion':['gini', 'entropy'],
    'splitter':['best','random'],
    
    'max_features':['auto','sqrt','log2']
}

In [12]:
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

In [13]:
grid.fit(X_train,y_train)

C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 12 candidates, totalling 36 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    3.7s
[Parallel(n_jobs=-1)]: Done  29 out of  36 | elapsed:    3.7s remaining:    0.8s
[Parallel(n_jobs=-1)]: Done  36 out of  36 | elapsed:    3.8s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=3)

In [14]:
grid_prediction=grid.predict(X_test)

In [15]:
grid_prediction

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0], dtype=uint8)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

In [17]:
print(cm)

[[45  0]
 [ 7 68]]

In [18]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)

In [19]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.87      1.00      0.93        45
           1       1.00      0.91      0.95        75

    accuracy                           0.94       120
   macro avg       0.93      0.95      0.94       120
weighted avg       0.95      0.94      0.94       120

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average='weighted')

In [21]:
print("F1 Best parameters{}:".format(grid.best_params_,f1_macro))

F1 Best parameters{'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}:

In [22]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9533333333333334

In [23]:
re=grid.cv_results_

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006817,0.000891,0.002153,0.001548,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.956989,0.935814,0.934046,0.942283,0.010424,11
1,0.004687,0.004381,0.004646,0.003327,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.978605,0.946077,0.978495,0.967725,0.015308,2
2,0.007896,0.001109,0.004352,0.002817,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.903487,0.936075,0.956721,0.932094,0.021915,12
3,0.010276,0.006680,0.005495,0.004713,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.978495,0.978495,0.946077,0.967689,0.015282,3
4,0.004773,0.000790,0.003532,0.000856,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.946077,0.957209,0.935082,0.946123,0.009034,8
5,0.005874,0.001593,0.003119,0.000844,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.925279,0.956989,0.956403,0.946224,0.014812,7
6,0.006933,0.001723,0.002629,0.000130,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.946381,0.957384,0.956403,0.953389,0.004971,6
7,0.006370,0.000708,0.007706,0.006017,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.946381,0.967829,0.967426,0.960546,0.010017,4
8,0.005384,0.000843,0.004000,0.000454,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.978495,0.978495,0.924507,0.960499,0.025450,5
9,0.006131,0.001088,0.002978,0.002426,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.989276,0.956989,0.967829,0.971365,0.013416,1
10,0.005686,0.000182,0.004007,0.000187,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.946381,0.915204,0.967426,0.943004,0.021453,10
11,0.003800,0.001258,0.003044,0.002273,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.945711,0.946818,0.945711,0.946080,0.000522,9

In [26]:
age=int(input("Enter your Age:"))
bp=float(input("Enter bp level:"))
al=float(input("Enter al level:"))
su=float(input("Enter su level:"))
bgr=float(input("Enter bgr level:"))
bu=float(input("Enter bu level:"))
sc=float(input("Enter sc level:"))
sod=float(input("Enter sod level:"))
pot=float(input("Enter pot level:"))
hrmo=float(input("Enter hrmo level:"))
pcv=float(input("Enter pcv level:"))
wc=float(input("Enter wc level:"))
rc=float(input("Enter rc level:"))
sg_b=int(input("Enter sg_b 0 or 1:"))
sg_c=int(input("Enter sg_c 0 or 1:"))
sg_d=int(input("Enter sg_d 0 or 1:"))
sg_e=int(input("Enter sg_e 0 or 1:"))
rbc_normal=int(input("Enter rbc_normal 0 or 1:"))
pc_normal=int(input("Enter pc_normal 0 or 1:"))
pcc_present=int(input("Enter pcc_present 0 or 1:"))
ba_present=int(input("Enter ba_present 0 or 1:"))
htn_yes=int(input("Enter htn_yes 0 or 1:"))
dm_yes=int(input("Enter dm_yes 0 or 1:"))
cad_yes=int(input("Enter cad_yes 0 or 1:"))
appet_yes=int(input("Enter appt_yes 0 or 1:"))
pe_yes=int(input("Enter pe_yes 0 or 1:"))
ane_yes=int(input("Enter ane_yes 0 or 1:"))

Enter your Age:35
Enter bp level:80
Enter al level:3
Enter su level:5
Enter bgr level:150
Enter bu level:51
Enter sc level:1
Enter sod level:140
Enter pot level:6
Enter hrmo level:12
Enter pcv level:50
Enter wc level:11200
Enter rc level:7
Enter sg_b 0 or 1:0
Enter sg_c 0 or 1:1
Enter sg_d 0 or 1:0
Enter sg_e 0 or 1:1
Enter rbc_normal 0 or 1:0
Enter pc_normal 0 or 1:0
Enter pcc_present 0 or 1:0
Enter ba_present 0 or 1:1
Enter htn_yes 0 or 1:1
Enter dm_yes 0 or 1:1
Enter cad_yes 0 or 1:1
Enter appt_yes 0 or 1:1
Enter pe_yes 0 or 1:1
Enter ane_yes 0 or 1:1

In [27]:
Future_predictions=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])

In [28]:
print("Future_predictions:{}".format(Future_predictions))

Future_predictions:[1]