In [42]:
import pandas as pd

In [43]:
dataset=pd.read_csv('CKD.csv')

In [44]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [45]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [46]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [47]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [48]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [49]:
dependent=dataset[['classification_yes']]

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [51]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [52]:
grid_params={'n_estimators':[10,100,1000],
             'criterion':['gini','entropy'],
             'max_features':['auto','sqrt','log2']
            }

In [53]:
grid=GridSearchCV(RandomForestClassifier(),grid_params,refit=True,verbose=0,n_jobs=-1,scoring='f1_weighted')

In [54]:
grid.fit(X_train,y_train)

C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Priya\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:715: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100, 1000]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_weighted', verbose=0)

In [55]:
grid_predictions=grid.predict(X_test)

In [56]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)
print(cm)

[[44  1]
 [ 1 74]]

In [57]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [58]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        45
           1       0.99      0.99      0.99        75

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

In [59]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9997037037037038

In [60]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("best parameters{}:".format(grid.best_params_,f1_macro))

best parameters{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 100}:

In [61]:
re=grid.cv_results_

In [62]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.027858,0.003174,0.004847,3.700997e-03,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.978495,0.946818,0.978361,0.967891,0.014901,14
1,0.144314,0.010944,0.010572,7.478224e-03,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.989215,0.957384,0.978361,0.974987,0.013212,1
2,1.228911,0.003045,0.099566,5.073413e-03,gini,auto,1000,"{'criterion': 'gini', 'max_features': 'auto', ...",0.989215,0.957384,0.978361,0.974987,0.013212,1
3,0.016772,0.000480,0.005364,3.793089e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.978495,0.925736,0.967646,0.957292,0.022749,16
4,0.123371,0.003841,0.007937,6.379816e-03,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.989215,0.957384,0.978361,0.974987,0.013212,1
5,1.213251,0.028093,0.105094,3.357380e-03,gini,sqrt,1000,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.989215,0.957384,0.978361,0.974987,0.013212,1
6,0.015022,0.001287,0.002682,3.792654e-03,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",0.956989,0.915204,0.967426,0.946540,0.022564,18
7,0.113846,0.004636,0.015623,2.247832e-07,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.967646,0.967977,0.978361,0.971328,0.004975,13
8,1.205767,0.010820,0.110404,7.693034e-03,gini,log2,1000,"{'criterion': 'gini', 'max_features': 'log2', ...",0.989215,0.957384,0.978361,0.974987,0.013212,1
9,0.019145,0.004449,0.005276,7.460891e-03,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.967646,0.925736,0.978361,0.957247,0.022708,17
10,0.128931,0.003107,0.010577,7.481686e-03,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.978361,0.946818,0.989215,0.971465,0.017982,11
11,1.258360,0.009397,0.111545,4.915305e-03,entropy,auto,1000,"{'criterion': 'entropy', 'max_features': 'auto...",0.989215,0.957384,0.978361,0.974987,0.013212,1
12,0.017235,0.003742,0.005408,3.823800e-03,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.989276,0.936271,0.989215,0.971588,0.024973,9
13,0.122570,0.001571,0.015622,1.946680e-07,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.978495,0.946818,0.978361,0.967891,0.014901,14
14,1.322926,0.009600,0.112327,3.427858e-03,entropy,sqrt,1000,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.978361,0.957384,0.978361,0.971368,0.009889,12
15,0.014543,0.005380,0.010522,7.440994e-03,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.936271,0.978361,0.971544,0.026460,10
16,0.129280,0.005763,0.010162,6.680430e-03,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",0.989215,0.957384,0.978361,0.974987,0.013212,1
17,1.231914,0.079007,0.088050,2.664964e-02,entropy,log2,1000,"{'criterion': 'entropy', 'max_features': 'log2...",0.989215,0.957384,0.978361,0.974987,0.013212,1

In [74]:
age=int(input("Enter your Age:"))
bp=float(input("Enter bp level:"))
al=float(input("Enter al level:"))
su=float(input("Enter su level:"))
bgr=float(input("Enter bgr level:"))
bu=float(input("Enter bu level:"))
sc=float(input("Enter sc level:"))
sod=float(input("Enter sod level:"))
pot=float(input("Enter pot level:"))
hrmo=float(input("Enter hrmo level:"))
pcv=float(input("Enter pcv level:"))
wc=float(input("Enter wc level:"))
rc=float(input("Enter rc level:"))
sg_b=int(input("Enter sg_b 0 or 1:"))
sg_c=int(input("Enter sg_c 0 or 1:"))
sg_d=int(input("Enter sg_d 0 or 1:"))
sg_e=int(input("Enter sg_e 0 or 1:"))
rbc_normal=int(input("Enter rbc_normal 0 or 1:"))
pc_normal=int(input("Enter pc_normal 0 or 1:"))
pcc_present=int(input("Enter pcc_present 0 or 1:"))
ba_present=int(input("Enter ba_present 0 or 1:"))
htn_yes=int(input("Enter htn_yes 0 or 1:"))
dm_yes=int(input("Enter dm_yes 0 or 1:"))
cad_yes=int(input("Enter cad_yes 0 or 1:"))
appet_yes=int(input("Enter appt_yes 0 or 1:"))
pe_yes=int(input("Enter pe_yes 0 or 1:"))
ane_yes=int(input("Enter ane_yes 0 or 1:"))

Enter your Age:35
Enter bp level:95
Enter al level:5
Enter su level:2
Enter bgr level:150
Enter bu level:5
Enter sc level:52
Enter sod level:24
Enter pot level:12
Enter hrmo level:25
Enter pcv level:54
Enter wc level:8500
Enter rc level:5
Enter sg_b 0 or 1:0
Enter sg_c 0 or 1:0
Enter sg_d 0 or 1:0
Enter sg_e 0 or 1:0
Enter rbc_normal 0 or 1:0
Enter pc_normal 0 or 1:1
Enter pcc_present 0 or 1:1
Enter ba_present 0 or 1:1
Enter htn_yes 0 or 1:1
Enter dm_yes 0 or 1:1
Enter cad_yes 0 or 1:0
Enter appt_yes 0 or 1:0
Enter pe_yes 0 or 1:0
Enter ane_yes 0 or 1:0

In [75]:
Future_predictions=grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])

In [76]:
print("Future_predictions:{}".format(Future_predictions))

Future_predictions:[1]

In [77]:
import pickle
filename='Randomforestfinalmodel.sav'
pickle.dump(grid,open(filename,'wb'))

In [78]:
loded_model=pickle.load(open('Randomforestfinalmodel.sav','rb'))

In [80]:
result=loded_model.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,
       wc, rc, sg_b, sg_c, sg_d, sg_e, rbc_normal, pc_normal,
       pcc_present, ba_present, htn_yes, dm_yes, cad_yes,
       appet_yes, pe_yes, ane_yes]])
result

array([1], dtype=uint8)